/**
 * Author:  sym410
 * Created: May 18, 2016
 */

CREATE TABLE Saldo
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conto DOUBLE PRECISION
);


CREATE TABLE Acquirente
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
    username VARCHAR(25), 
    psw VARCHAR(25),
    saldo_id INTEGER,
    FOREIGN KEY (saldo_id) REFERENCES saldo(id)
);


CREATE TABLE Venditore
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(25), 
    psw VARCHAR(25),
    saldo_id INTEGER,
    FOREIGN KEY (saldo_id) REFERENCES saldo(id)
);



CREATE TABLE ObjectSale
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256),
    url VARCHAR(256),
    quantity INTEGER,
    description VARCHAR(256),
    price DOUBLE PRECISION,
    category VARCHAR(64),
    venditore_id INTEGER,
    FOREIGN KEY(venditore_id) REFERENCES venditore(id)
);